# docker-compose.yml
version: '3.8'

services:
  client:
    build:
      context: ./backend
    ports:
      - "80:80"

  server:
    build:
      context: ./frontend
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: library
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
